package game.sourcecode;

public enum ButtonName {
    BIG_BUTTON_STATUS_1, BIG_BUTTON_STATUS_2, BIG_BUTTON_STATUS_3, SMALL_BUTTON_STATUS_1, SMALL_BUTTON_STATUS_2, SMALL_BUTTON_STATUS_3,
    SWITCH_BUTTON_ON, SWITCH_BUTTON_OFF, REPEAL_1, REPEAL_2, REPEAL_3, APPROVE_1, APPROVE_2, APPROVE_3,
    SOUND_ON, SOUND_ON_1, SOUND_OFF, SOUND_OFF_1, SOUND_UP_1, SOUND_UP_2, SOUND_UP_3, SOUND_DOWN_1, SOUND_DOWN_2, SOUND_DOWN_3,
    NEXT_BGM_1, NEXT_BGM_3, NEXT_BGM_2,JOIN,TEXTFRAME
}
